language: objective-c

xcode_project: STW3CDateFormatter.xcodeproj
matrix:
    include:
        - xcode_sdk: iphonesimulator7.1
          xcode_scheme: STW3CDateFormatter-iOS
        - xcode_sdk: macosx
          xcode_scheme: STW3CDateFormatter-mac

branches:
  only:
    - master

before_script:
    - brew uninstall xctool && brew install xctool --HEAD
